# Define a 'Service' To Expose mysql to Other Services
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}  # DNS name 
  labels:
    app: {{ .Values.appName }}
    tier: {{ .Values.appTierdb }}
spec:
  ports:
    - port: {{ .Values.serviceport }}
      targetPort: {{ .Values.servicetargetport }}
  selector:       # mysql Pod Should contain same labels
    app: {{ .Values.appName }}
    tier: {{ .Values.appTierdb }}
  clusterIP: {{ .Values.servicetype }}  # We Use DNS, Thus ClusterIP is not relevant
